(function () {
  'use strict';
  let freezeLog = JSON.parse(localStorage.getItem('lc.freezeLog') || '[]');
  let contamLog = JSON.parse(localStorage.getItem('lc.contamLog') || '[]');
  let mycoLog = JSON.parse(localStorage.getItem('lc.mycoLog') || '[]');

  LC.registerView('cellculture', function () {
    const root = document.createElement('div');
    let tab = 'split';
    root.innerHTML = `<div class="view-header"><h1 class="view-title">🦠 Cell Culture</h1><p class="view-subtitle">Splitting, freezing, counting, and contamination logs.</p></div>
      <div class="tabs"><button class="tab active" data-tab="split">Split / Passage</button><button class="tab" data-tab="freeze">Freeze / Thaw</button><button class="tab" data-tab="media">Media recipes</button><button class="tab" data-tab="log">Logs</button></div><div id="cct"></div>`;

    function render() {
      root.querySelectorAll('.tab').forEach(t => t.classList.toggle('active', t.dataset.tab === tab));
      const h = root.querySelector('#cct');
      const $ = id => root.querySelector('#' + id);

      if (tab === 'split') {
        h.innerHTML = `<div class="card"><div class="card-sub">Calculate seeding volume for subculturing.</div><div class="grid grid-2"><div><div class="field"><label class="label">Current confluency (%)</label><input class="input" id="spConf" type="number" value="90" /></div><div class="field"><label class="label">Vessel type</label><select class="select" id="spVes"><option value="25">T25 flask</option><option value="75" selected>T75 flask</option><option value="175">T175 flask</option><option value="35">35 mm dish</option><option value="60">60 mm dish</option><option value="100">100 mm dish</option></select></div><div class="field"><label class="label">Split ratio (1:n)</label><input class="input" id="spRatio" type="number" value="4" /></div><div class="field"><label class="label">New vessel</label><select class="select" id="spNewVes"><option value="25">T25</option><option value="75" selected>T75</option><option value="175">T175</option><option value="35">35 mm</option><option value="60">60 mm</option><option value="100">100 mm</option></select></div></div><div><div class="card-title">Surface area reference</div><div class="table-wrap"><table class="table"><thead><tr><th>Vessel</th><th>Area (cm²)</th><th>Seeding cells</th></tr></thead><tbody><tr><td>T25 flask</td><td class="mono">25</td><td class="mono">5 × 10⁵</td></tr><tr><td>T75 flask</td><td class="mono">75</td><td class="mono">1.5 × 10⁶</td></tr><tr><td>T175 flask</td><td class="mono">175</td><td class="mono">3.5 × 10⁶</td></tr><tr><td>35 mm dish</td><td class="mono">9.6</td><td class="mono">2 × 10⁵</td></tr><tr><td>60 mm dish</td><td class="mono">28.3</td><td class="mono">5 × 10⁵</td></tr><tr><td>100 mm dish</td><td class="mono">78.5</td><td class="mono">1.5 × 10⁶</td></tr></tbody></table></div></div></div>
          <div class="result highlight" id="spRes"></div></div>`;
        const areas = { '25':25,'75':75,'175':175,'35':9.6,'60':28.3,'100':78.5 };
        const calc = () => { const conf=+$('spConf').value,ves=$('spVes').value,ratio=+$('spRatio').value,nv=$('spNewVes').value; if(!conf) return; const cellsInOptimal=areas[ves]; const newArea=areas[nv]; const vol=(newArea/cellsInOptimal)*(conf/100); $('spRes').innerHTML=`From a ${ves} cm² flask at ${conf}% confluence at 1:${ratio} split:<br>Transfer <strong>${(vol*10).toFixed(1)} µL</strong> of resuspended cells to new ${nv} cm² flask.<br><em>Assuming 1×10⁶ cells/cm² at 100% confluence.</em>`; };
        ['spConf','spVes','spRatio','spNewVes'].forEach(id => root.querySelector('#'+id).addEventListener('input', calc)); calc();
      } else if (tab === 'freeze') {
        h.innerHTML = `<div class="card"><div class="card-sub">Freeze mammalian cells in 10% DMSO + 90% FBS (or 10% DMSO + 50% FBS + 40% growth media).</div><div class="grid grid-2"><div><div class="card-title">Freezing calculator</div><div class="field"><label class="label">Number of vials</label><input class="input" id="frN" type="number" value="5" /></div><div class="field"><label class="label">Volume per vial (mL)</label><div class="input-with-suffix"><input class="input" id="frV" type="number" value="1" /><span class="suffix">mL</span></div></div><div class="field"><label class="label">DMSO (%)</label><input class="input" id="frD" type="number" value="10" /></div><div class="result highlight" id="frRes"></div></div><div><div class="card-title">Freeze log</div><div class="input-group"><input class="input" id="flCell" placeholder="Cell line" /><input class="input" id="flPass" type="number" placeholder="Passage" /><input class="input" id="flDate" type="date" /><button class="btn btn-primary" id="flAdd">Log</button></div><div class="list" id="flList" style="margin-top:8px;"></div></div></div></div>`;
        const calcF = () => { const n=+$('frN').value,v=+$('frV').value,d=+$('frD').value; if(!n) return; const tot=n*v; const dmso=tot*d/100; const fbs=tot*0.9-dmso; const cells=tot*0.1; $('frRes').innerHTML=`Total: <strong>${tot.toFixed(1)} mL</strong><br>DMSO: <strong>${dmso.toFixed(1)} mL</strong><br>FBS: <strong>${(fbs+dmso).toFixed(1)} mL</strong> (${d}% DMSO)<br>Cells: <strong>${(cells/tot*1e6).toFixed(0)} cells</strong><br><br><em>Freeze at -80°C overnight, transfer to LN₂ next day.</em>`; };
        ['frN','frV','frD'].forEach(id => root.querySelector('#'+id).addEventListener('input', calcF)); calcF();
        function renderFL() { const lst=root.querySelector('#flList'); if(freezeLog.length===0){lst.innerHTML='<div class="list-empty">No freeze records.</div>';return;} lst.innerHTML=freezeLog.slice().reverse().map(l=>`<div class="list-item"><div class="grow"><span style="font-weight:600;">${LC.esc(l.cell)}</span> <span class="card-sub">p${l.pass}</span></div><span>${l.date||''}</span><button class="btn btn-ghost btn-sm" data-fdel="${l.id}">🗑</button></div>`).join(''); lst.querySelectorAll('[data-fdel]').forEach(b=>b.addEventListener('click',()=>{freezeLog=freezeLog.filter(x=>x.id!==b.dataset.fdel);localStorage.setItem('lc.freezeLog',JSON.stringify(freezeLog));renderFL();})); }
        root.querySelector('#flAdd').addEventListener('click',()=>{const c=root.querySelector('#flCell').value.trim(),p=root.querySelector('#flPass').value,d=root.querySelector('#flDate').value;if(!c)return;freezeLog.unshift({id:LC.uid(),cell:c,pass:p,date:d,added:new Date().toISOString()});localStorage.setItem('lc.freezeLog',JSON.stringify(freezeLog));['flCell','flPass','flDate'].forEach(id=>root.querySelector('#'+id).value='');renderFL();}); renderFL();
      } else if (tab === 'media') {
        h.innerHTML = `<div class="card"><div class="card-title">Common cell culture media</div><div class="table-wrap"><table class="table"><thead><tr><th>Media</th><th>Base</th><th>Supplements</th><th>Use for</th></tr></thead><tbody><tr><td><strong>Complete DMEM</strong></td><td>DMEM</td><td>10% FBS, 1% P/S</td><td>HeLa, MCF-7, A549, HCT116, U87, 293T</td></tr><tr><td><strong>Complete RPMI</strong></td><td>RPMI-1640</td><td>10% FBS, 1% P/S</td><td>PC-3, DU145, Jurkat, K562, THP-1</td></tr><tr><td><strong>McCoy's 5A</strong></td><td>McCoy's 5A</td><td>10% FBS, 1% P/S</td><td>SKOV3, HT-29, SK-BR-3</td></tr><tr><td><strong>Ham's F-12K</strong></td><td>Kaighn's F-12K</td><td>10% FBS, 1% P/S</td><td>PC-12 (neuronal)</td></tr><tr><td><strong>DMEM/F12 mix</strong></td><td>1:1 DMEM:F12</td><td>10% FBS, 1% P/S</td><td>Primary cells, stem cells</td></tr><tr><td><strong>Freezing medium</strong></td><td>90% FBS + 10% DMSO</td><td>—</td><td>All mammalian cell lines</td></tr></tbody></table></div></div>`;
      } else {
        h.innerHTML = `<div class="card"><div class="card-title">Contamination log</div><div class="input-group"><input class="input" id="clCell" placeholder="Cell line" /><input class="input" id="clDate" type="date" /><select class="select" id="clType" style="max-width:180px;"><option value="bacterial">Bacterial</option><option value="fungal">Fungal / Yeast</option><option value="mycoplasma">Mycoplasma (+ve)</option><option value="cross">Cross-contamination</option></select><button class="btn btn-primary" id="clAdd">Log</button></div><div class="list" id="clList"></div></div>
          <div class="card"><div class="card-title">Mycoplasma test log</div><div class="input-group"><input class="input" id="mlCell" placeholder="Cell line" /><input class="input" id="mlDate" type="date" /><select class="select" id="mlRes" style="max-width:120px;"><option value="neg">Negative ✓</option><option value="pos">Positive ✗</option></select><button class="btn btn-primary" id="mlAdd">Log</button></div><div class="list" id="mlList"></div></div>`;
        function renderCL() { const lst=root.querySelector('#clList'); if(contamLog.length===0){lst.innerHTML='<div class="list-empty">No contamination events.</div>';return;} lst.innerHTML=contamLog.slice().reverse().map(l=>`<div class="list-item"><div class="grow"><span style="font-weight:600;">${LC.esc(l.cell)}</span> <span class="badge badge-${l.type==='bacterial'?'danger':'warn'}">${l.type}</span></div><span>${l.date||''}</span><button class="btn btn-ghost btn-sm" data-cdel="${l.id}">🗑</button></div>`).join(''); lst.querySelectorAll('[data-cdel]').forEach(b=>b.addEventListener('click',()=>{contamLog=contamLog.filter(x=>x.id!==b.dataset.cdel);localStorage.setItem('lc.contamLog',JSON.stringify(contamLog));renderCL();})); }
        function renderML() { const lst=root.querySelector('#mlList'); if(mycoLog.length===0){lst.innerHTML='<div class="list-empty">No mycoplasma tests.</div>';return;} lst.innerHTML=mycoLog.slice().reverse().map(l=>`<div class="list-item"><div class="grow"><span style="font-weight:600;">${LC.esc(l.cell)}</span></div><span class="badge badge-${l.result==='neg'?'success':'danger'}">${l.result==='neg'?'✓ Neg':'✗ Pos'}</span><span style="margin-left:8px;">${l.date||''}</span><button class="btn btn-ghost btn-sm" data-mdel="${l.id}">🗑</button></div>`).join(''); lst.querySelectorAll('[data-mdel]').forEach(b=>b.addEventListener('click',()=>{mycoLog=mycoLog.filter(x=>x.id!==b.dataset.mdel);localStorage.setItem('lc.mycoLog',JSON.stringify(mycoLog));renderML();})); }
        root.querySelector('#clAdd').addEventListener('click',()=>{const c=root.querySelector('#clCell').value.trim(),d=root.querySelector('#clDate').value,t=root.querySelector('#clType').value;if(!c)return;contamLog.unshift({id:LC.uid(),cell:c,date:d,type:t,added:new Date().toISOString()});localStorage.setItem('lc.contamLog',JSON.stringify(contamLog));['clCell','clDate'].forEach(id=>root.querySelector('#'+id).value='');renderCL();});
        root.querySelector('#mlAdd').addEventListener('click',()=>{const c=root.querySelector('#mlCell').value.trim(),d=root.querySelector('#mlDate').value,r=root.querySelector('#mlRes').value;if(!c)return;mycoLog.unshift({id:LC.uid(),cell:c,date:d,result:r,added:new Date().toISOString()});localStorage.setItem('lc.mycoLog',JSON.stringify(mycoLog));['mlCell','mlDate'].forEach(id=>root.querySelector('#'+id).value='');renderML();});
        renderCL(); renderML();
      }
    }
    root.querySelectorAll('.tab').forEach(t => t.addEventListener('click', () => { tab = t.dataset.tab; render(); }));
    render(); return root;
  });
})();
