(function () {
  'use strict';
  LC.registerView('settings', function () {
    const root = document.createElement('div');
    root.innerHTML = `<div class="view-header"><h1 class="view-title">⚙️ Settings</h1><p class="view-subtitle">App preferences, data export, and about.</p></div>
      <div class="card"><div class="card-title">Appearance</div><div class="field"><label class="label">Theme</label><select class="select" id="sTheme"><option value="light" ${LC.State.theme==='light'?'selected':''}>Light</option><option value="dark" ${LC.State.theme==='dark'?'selected':''}>Dark</option></select></div><div class="card-sub">Switch anytime via the ☀/🌙 icon in the top right.</div></div>
      <div class="card"><div class="card-title">Data</div><div class="card-sub">All your data is stored locally in this browser. Use export to back up or move between devices.</div><div style="display:flex; gap:8px; flex-wrap:wrap; margin-top:8px;"><button class="btn btn-primary" id="sExport">⤓ Export all data (JSON)</button><button class="btn" id="sImport">⤒ Import data</button><input type="file" id="sFile" accept=".json" style="display:none;" /><button class="btn btn-danger" id="sReset">⚠ Reset all data</button></div></div>
      <div class="card"><div class="card-title">About</div><p>Lab Companion — your pocket toolkit for cancer biology research.</p><p class="card-sub">Built for PhD scholars and research staff who work with Western blots, gel electrophoresis, cell culture, immunocytochemistry, and PCR. All data stays on your device.</p><p class="card-sub">Version 1.0 · ${new Date().getFullYear()}</p></div>`;

    root.querySelector('#sTheme').addEventListener('change', e => { LC.State.theme = e.target.value; document.documentElement.setAttribute('data-theme', LC.State.theme); LC.S.set('theme', LC.State.theme); });
    root.querySelector('#sExport').addEventListener('click', () => { const data = { version:1, exported:new Date().toISOString(), timers:LC.State.timers, notebook:LC.State.notebook, tasks:LC.State.tasks, inventory:LC.State.inventory, customRecipes:LC.State.customRecipes, theme:LC.State.theme, settings:LC.State.settings, freezeLog:JSON.parse(localStorage.getItem('lc.freezeLog')||'[]'), contamLog:JSON.parse(localStorage.getItem('lc.contamLog')||'[]'), mycoLog:JSON.parse(localStorage.getItem('lc.mycoLog')||'[]'), worldClock:JSON.parse(localStorage.getItem('lc.worldClock')||'null') }; const blob = new Blob([JSON.stringify(data,null,2)],{type:'application/json'}); const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download=`lab-companion-backup-${new Date().toISOString().slice(0,10)}.json`; a.click(); URL.revokeObjectURL(url); });
    root.querySelector('#sImport').addEventListener('click', () => root.querySelector('#sFile').click());
    root.querySelector('#sFile').addEventListener('change', e => { const f=e.target.files[0]; if(!f)return; const reader=new FileReader(); reader.onload=ev=>{try{const d=JSON.parse(ev.target.result); if(d.timers){LC.State.timers=d.timers;LC.saveTimers();} if(d.notebook){LC.State.notebook=d.notebook;LC.saveNotebook();} if(d.tasks){LC.State.tasks=d.tasks;LC.saveTasks();} if(d.inventory){LC.State.inventory=d.inventory;LC.saveInventory();} if(d.customRecipes){LC.State.customRecipes=d.customRecipes;LC.saveCustomRecipes();} if(d.theme){LC.State.theme=d.theme;LC.S.set('theme',d.theme);document.documentElement.setAttribute('data-theme',d.theme);} if(d.freezeLog)localStorage.setItem('lc.freezeLog',JSON.stringify(d.freezeLog)); if(d.contamLog)localStorage.setItem('lc.contamLog',JSON.stringify(d.contamLog)); if(d.mycoLog)localStorage.setItem('lc.mycoLog',JSON.stringify(d.mycoLog)); if(d.worldClock)localStorage.setItem('lc.worldClock',JSON.stringify(d.worldClock)); LC.toast('Data imported — reloading','success'); setTimeout(()=>location.reload(),800); }catch(err){LC.toast('Invalid file','danger');}}; reader.readAsText(f); });
    root.querySelector('#sReset').addEventListener('click', () => { if(!confirm('This will delete ALL your data. Continue?'))return; Object.keys(localStorage).filter(k=>k.startsWith('lc.')).forEach(k=>localStorage.removeItem(k)); LC.toast('Reset complete — reloading','warn'); setTimeout(()=>location.reload(),800); });
    return root;
  });
})();
