(function () {
  'use strict';
  LC.registerView('western', function () {
    const root = document.createElement('div');
    let tab = 'gel';
    root.innerHTML = `<div class="view-header"><h1 class="view-title">🧫 Western Blot</h1><p class="view-subtitle">Gel percentage, transfer conditions, antibody dilutions, and protocol timer.</p></div>
      <div class="tabs"><button class="tab active" data-tab="gel">Gel %</button><button class="tab" data-tab="transfer">Transfer</button><button class="tab" data-tab="ab">Antibody dilutions</button><button class="tab" data-tab="loading">Loading &amp; sample prep</button><button class="tab" data-tab="protocol">Protocol timer</button></div><div id="wbct"></div>`;

    function render() {
      root.querySelectorAll('.tab').forEach(t => t.classList.toggle('active', t.dataset.tab === tab));
      const h = root.querySelector('#wbct');
      const $ = id => root.querySelector('#' + id);
      if (tab === 'gel') {
        h.innerHTML = `<div class="card"><div class="card-sub">Choose gel % by target protein size, or reverse-lookup by %.</div><div class="grid grid-2"><div><div class="card-title">By protein size</div><div class="field"><label class="label">Target MW (kDa)</label><input class="input" id="wMw" type="number" value="50" step="0.5" /></div><div class="result highlight" id="wRes1">—</div></div><div><div class="card-title">Reference</div><div class="table-wrap"><table class="table"><thead><tr><th>Gel %</th><th>Optimal range (kDa)</th><th>Use for</th></tr></thead><tbody><tr><td class="mono"><strong>Tricine 16%</strong></td><td class="mono">2 – 20</td><td>Small proteins, peptides</td></tr><tr><td class="mono"><strong>15%</strong></td><td class="mono">10 – 30</td><td>Histones, cytokines</td></tr><tr><td class="mono"><strong>12%</strong></td><td class="mono">20 – 80</td><td>Most signaling proteins</td></tr><tr><td class="mono"><strong>10%</strong></td><td class="mono">30 – 100</td><td>Standard WB, caspases</td></tr><tr><td class="mono"><strong>8%</strong></td><td class="mono">60 – 200</td><td>Receptors, kinases</td></tr><tr><td class="mono"><strong>6%</strong></td><td class="mono">100 – 300</td><td>Large complexes, mTOR</td></tr><tr><td class="mono"><strong>4-20% grad</strong></td><td class="mono">10 – 250</td><td>Mixed lysates</td></tr></tbody></table></div></div></div></div>`;
        const calc = () => { const mw = +$('wMw').value; let g = '10%', note = ''; if (mw <= 20) { g = 'Tricine 16% or 15%'; note = 'Use 15% if not using tricine.'; } else if (mw <= 30) g = '15%'; else if (mw <= 60) g = '12%'; else if (mw <= 100) g = '10%'; else if (mw <= 200) g = '8%'; else g = '6% (or 4-20% gradient)'; $('wRes1').innerHTML = `Use <strong>${g}</strong> gel. ${note}`; };
        $('wMw').addEventListener('input', calc); calc();
      } else if (tab === 'transfer') {
        h.innerHTML = `<div class="card"><div class="card-sub">Voltage and time settings for protein transfer to membrane.</div><div class="table-wrap"><table class="table"><thead><tr><th>Method</th><th>Voltage</th><th>Time</th><th>Notes</th></tr></thead><tbody>${LC_DATA.transferPresets.map(p => `<tr><td>${p.method}</td><td class="mono">${p.volt} V</td><td class="mono">${p.time} min</td><td>${p.notes}</td></tr>`).join('')}</tbody></table></div><div class="card-title" style="margin-top:16px;">Quick timer</div><div class="input-group"><input class="input" id="tfH" type="number" value="1" min="0" /><input class="input" id="tfM" type="number" value="30" min="0" /><button class="btn btn-primary" id="tfGo">Start transfer timer</button></div><div class="card-sub">hours · minutes</div></div>`;
        h.querySelector('#tfGo').addEventListener('click', () => { const hr = +h.querySelector('#tfH').value||0, mn = +h.querySelector('#tfM').value||0; const s = hr*3600+mn*60; if (s<=0) return; LC.addTimer('Western transfer', s); LC.toast('Transfer timer started', 'success'); LC.navigate('timers'); });
      } else if (tab === 'ab') {
        h.innerHTML = `<div class="card"><div class="card-sub">Typical working dilutions — always titrate to your antibody and sample.</div>${Object.entries(LC_DATA.antibodyDilutions).map(([k,v]) => `<div class="card-title" style="margin-top:12px;">${k}</div><div class="table-wrap"><table class="table"><thead><tr><th>Reagent</th><th>Recommended dilution</th></tr></thead><tbody>${Object.entries(v).map(([r,d]) => `<tr><td>${r}</td><td class="mono">${d}</td></tr>`).join('')}</tbody></table></div>`).join('')}<div class="card-title" style="margin-top:16px;">Custom dilution</div><div class="grid grid-2"><div class="field"><label class="label">Stock concentration</label><div class="input-with-suffix"><input class="input" id="abS" type="number" value="1" /><span class="suffix">mg/mL</span></div></div><div class="field"><label class="label">Working concentration</label><div class="input-with-suffix"><input class="input" id="abW" type="number" value="1" /><span class="suffix">µg/mL</span></div></div><div class="field"><label class="label">Final volume</label><div class="input-with-suffix"><input class="input" id="abV" type="number" value="10" /><span class="suffix">mL</span></div></div></div><div class="result highlight" id="abRes">—</div></div>`;
        const calc = () => { const s=+$('abS').value,w=+$('abW').value,v=+$('abV').value; if(!s||!w||!v) return; const dil=s*1000/w; const vol=(v/dil)*1000; $('abRes').innerHTML=`Dilution <strong>1:${Math.round(dil)}</strong> → add <strong>${vol.toFixed(2)} µL</strong> antibody + diluent to ${v} mL.`; };
        ['abS','abW','abV'].forEach(id => root.querySelector('#'+id).addEventListener('input', calc)); calc();
      } else if (tab === 'loading') {
        h.innerHTML = `<div class="card"><div class="card-sub">Loading amount and buffer prep.</div><div class="grid grid-2"><div><div class="card-title">Per-well loading</div><div class="field"><label class="label">Stock concentration</label><div class="input-with-suffix"><input class="input" id="lpS" type="number" value="2" step="0.1" /><span class="suffix">mg/mL</span></div></div><div class="field"><label class="label">Target load</label><div class="input-with-suffix"><input class="input" id="lpT" type="number" value="20" /><span class="suffix">µg</span></div></div><div class="field"><label class="label"># lanes</label><input class="input" id="lpN" type="number" value="10" /></div><div class="result highlight" id="lpRes">—</div></div><div><div class="card-title">Recommended load</div><div class="table-wrap"><table class="table"><thead><tr><th>Sample</th><th>Load / lane</th></tr></thead><tbody><tr><td>Whole cell lysate</td><td class="mono">10 – 30 µg</td></tr><tr><td>Tissue homogenate</td><td class="mono">20 – 50 µg</td></tr><tr><td>Purified protein</td><td class="mono">0.1 – 2 µg</td></tr><tr><td>IP eluate</td><td class="mono">20 µL</td></tr><tr><td>Co-IP (low abundance)</td><td class="mono">50 – 100 µg</td></tr></tbody></table></div></div></div></div>`;
        const calc = () => { const s=+$('lpS').value,t=+$('lpT').value,n=+$('lpN').value; if(!s||!t) return; const vpl=(t/s); const total=vpl*n; $('lpRes').innerHTML=`Per lane: <strong>${vpl.toFixed(1)} µL</strong> sample + buffer (1:4 = +${(vpl/3).toFixed(1)} µL 4× Laemmli). Total sample: <strong>${total.toFixed(1)} µL</strong>.`; };
        ['lpS','lpT','lpN'].forEach(id => root.querySelector('#'+id).addEventListener('input', calc)); calc();
      } else {
        h.innerHTML = `<div class="card"><div class="card-sub">Run a full Western protocol — click a step to start its timer.</div><div class="list" id="wbSteps"></div><div class="card-title" style="margin-top:16px;">Custom step</div><div class="input-group"><input class="input" id="wbSN" placeholder="Step name" /><input class="input" id="wbSM" type="number" placeholder="minutes" /><button class="btn btn-primary" id="wbAS">+ Add</button></div></div>`;
        const steps = [
          { n:'Sample prep (lysis + boil 5 min @ 95°C)', m:5 },{ n:'Load gel + SDS-PAGE run', m:90 },{ n:'Transfer (wet, 100V, ice)', m:90 },{ n:'Ponceau / total protein stain', m:5 },{ n:'Block (5% milk/TBST, RT)', m:60 },{ n:'Primary antibody (4°C)', m:720 },{ n:'TBST washes (3×, 5 min each)', m:15 },{ n:'Secondary antibody (RT)', m:60 },{ n:'Final TBST washes (3×, 5 min each)', m:15 },{ n:'ECL development & image', m:10 }
        ];
        h.querySelector('#wbSteps').innerHTML = steps.map((s,i) => `<div class="list-item"><div class="grow"><div style="font-weight:600;">${i+1}. ${s.n}</div><div class="card-sub">${s.m} min</div></div><button class="btn btn-sm btn-primary" data-s="${i}">⏱ Start</button></div>`).join('');
        h.querySelectorAll('[data-s]').forEach(b => b.addEventListener('click', () => { const s=steps[+b.dataset.s]; LC.addTimer(s.n, s.m*60); LC.toast(`Started: ${s.n}`,'success'); LC.navigate('timers'); }));
        h.querySelector('#wbAS').addEventListener('click', () => { const n=h.querySelector('#wbSN').value.trim(), m=+h.querySelector('#wbSM').value; if(!n||!m) return; LC.addTimer(n, m*60); LC.toast(`Started: ${n}`,'success'); });
      }
    }
    root.querySelectorAll('.tab').forEach(t => t.addEventListener('click', () => { tab = t.dataset.tab; render(); }));
    render(); return root;
  });
})();
